### ISSUE TITLE
Problem with bootstrap component like <label></label> 

### ISSUE THREAD

**Issue by stefanobasta** [cosmocode/edittable#121]
When a bootstrap component (https://www.dokuwiki.org/plugin:bootswrapper) like <label> is integrated in the table, the content between the comments will be doubled for each edit/save loop.
e.g.: <label>Hello</label> => <label>HelloHello</label> => <label>HelloHelloHelloHello</label>

**Comment by micgro42** [comment]
I can reproduce the problem. However, this does not appear to be an edittable problem since specifically the content of the bootswrapper-tag gets duplicated. For example content inside of tags of the wrap plugin is unaffected.

I will mark edittable as conflicting with bootswrapper until the problem is resolved at their end.

**Comment by darkblinded** [comment]
Has this issue been resolved yet? Because although this issue has been closed, I'm still experiencing this bug.

**Comment by micgro42** [comment]
@darkblinded As stated in my closing comment, this seems to be an issue with the bootswrapper-plugin, not edittable.
