### ISSUE TITLE
Fw: Tooltip inside a table cell gets duplicated while EditTable is used

### ISSUE THREAD

**Issue by regystro** [cosmocode/edittable#135]
Hi.

Would you mind having a look at this issue?: https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/issues/68

Thank you in advance.

**Comment by MvErven** [comment]
I see it's a duplicate with https://github.com/cosmocode/edittable/issues/121

**Comment by micgro42** [comment]
I can reproduce the problem. However, this does not appear to be an edittable problem since specifically the content of the bootswrapper-tag gets duplicated. For example content inside of tags of the wrap plugin is unaffected.

I will mark edittable as conflicting with bootswrapper until the problem is resolved at their end.
