### ISSUE TITLE
PHP warning on Release "Igor": Undefined array key "hide"

### ISSUE THREAD

**Issue by dokuser** [cosmocode/edittable#218]
On Release 2022-07-31 "Igor", I'm getting the following PHP warning when saving pages containing tables edited with edittable.

`PHP Warning:  Undefined array key "hide" in [...]\lib\plugins\edittable\action\editor.php on line 217`

**Comment by eshimae** [comment]
In my environment, this plugin worked fine with Igor.
However, when I updated the php version from 7.4 to 8.0, a similar error occurred.
I believe the problem is due to the php version and not the dokuwiki version.

Security support for php7.4 has ended, so I hope this plugin will support php8.x as soon as possible.

**Comment by torjin-dot** [comment]
Hi, it also happens with php 8.1. Maybe the maintainer can help here, but it needs definitely a code bug fix in the plugin.

**Comment by imic6** [comment]
I made a pull request for a fix.
[https://github.com/cosmocode/edittable/pull/222](https://github.com/cosmocode/edittable/pull/222)
