### ISSUE TITLE
Monobook problem

### ISSUE THREAD

**Issue by mmatloha** [cosmocode/edittable#70]
Edittable Right-click context menu doesn't work in monobook template - at all.

PS:It's working in dokuwiki template.

I use 
=====
- Dokuwiki Release 2014-09-29b "Hrun"
- 2014-02-09 monobook template
- 2014-06-18 Edittable Plugin

**Comment by karthik1516** [comment]
I love the editable plugin and use it all day. This problem is bit of an inconvenience. The only workaround is to add a row manually and then edit. Tried switching to dokuwiki template instead of monoblock. But, monoblock is significantly a better template, so I wish to keep monoblock. I will greatly appreciate if you can resolve this issue.

**Comment by mmatloha** [comment]
I switched from monobook to vector template. Its maintained by the same person.
Its similar to monobook and Editable is working just well.

**Comment by karthik1516** [comment]
I switched to vector and works perfect. Thanks!

**Comment by thewarden** [comment]
I experienced the same issue. However since Vector is very similar to Monobook, I switched to Vector template and the issue was gone. Thanks karthik1516 for the suggestion.

**Comment by splitbrain** [comment]
should be fixed in monobook template
