### ISSUE TITLE
feature wish - compatibility with sortable tables

### ISSUE THREAD

**Issue by sleslie** [cosmocode/edittable#72]
I have resisted deploying this plugin as it is marked as conflicting with sortable tables, something we use a lot of. But I would love to be able to use it. Is there any way to incorporate either the code or the functionality from sorttables plugin?

**Comment by konus1** [comment]
I would like to use the sortablejs-plugin and even more the searchtablejs-plugin. Is there any hope of resolving this conflicts?

**Comment by konus1** [comment]
I found out, that the **sortable** plugin is compatible since [Version 2.5 (2011-05-10)](https://www.dokuwiki.org/plugin:sortablejs#fixes)
The **searchtable** plugin can be [made compatible](https://github.com/xdreamer/searchtablejs/issues/2) when adding the line
`function getAllowedTypes() {return array('container','formatting','substition');}`
to searchtablejs\syntax.php
